export {Home} from './Home'
export {Popular} from './Popular'
export {TopRated} from './TopRated'
export {Favorites} from './Favorites'
export {NowPlaying} from './NowPlaying'
export {Upcoming} from './Upcoming'